### ISSUE TITLE
Unlock trophies

### ISSUE THREAD

**Issue by Sup3820** [TheRouletteBoi/MaxPayne3#1]
Any possibility you can add the ability for unlocking trophies, and make them selectable, so user can pick which ones they want to unlock?

Or would this work and then just bind to a button press?
```
void UnlockAchievements()
{
    int i = 0;
    while(i < 66)
    {
        if(!HAS_ACHIEVEMENT_BEEN_PASSED(i)) AWARD_ACHIEVEMENT(i);
        i++;
    }
}
```

**Comment by TheRouletteBoi** [comment]
the code you provided would only unlock all trophies

**Comment by TheRouletteBoi** [comment]
the code you provided would only unlock all trophies

**Comment by Sup3820** [comment]
How would I go about unlocking specific trophies?

**Comment by TheRouletteBoi** [comment]
you would need to find the trophy name by index

so something like and check the name when it is displayed on screen
AWARD_ACHIEVEMENT(0); // first trophy
AWARD_ACHIEVEMENT(1); // second trophy
AWARD_ACHIEVEMENT(2); // third trophy
AWARD_ACHIEVEMENT(3); // fourth trophy
ect...

**Comment by Sup3820** [comment]
Thanks I will close this now. I will submit a pull request once I have this implemented thanks
